name: mobile_assessment_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  #splash screen
  animated_splash_screen: ^1.3.0

  # format date time
  intl: ^0.17.0
  #pin Input Field
  pinput: ^2.2.9
  #intl phone field
  intl_phone_field: ^3.1.0
  #datetime_picker_formfield: ^2.0.0

  #emailValidator
  email_validator: ^2.0.1

  #provider
  provider: ^6.0.2

  # auth with mail,google
  firebase_core: ^1.16.0
  firebase_auth: ^3.3.17
  cloud_firestore:


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.2.7

flutter_native_splash:
  color: "#000000"


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf

